### ISSUE TITLE
大佬，请问怎么为自己的插件添加图标？

### ISSUE THREAD

**Issue by Coldvvater** [Peng-YM/Loon-Gallery#9]
插件仓库里其他大佬的插件是有图标的，而有些则没有，是一个“？”，请问怎么添加？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Peng-YM** [comment]
可以看一下 Loon 的插件语法

#icon=xxx.png

**Comment by Coldvvater** [comment]
> 可以看一下 Loon 的插件语法
> 
> #icon=xxx.png

明白了，谢谢
